# Generated by Django 3.2 on 2021-04-23 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driverAPI', '0001_initial'),
        ('passengerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverhistory',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengerAPI.passenger'),
        ),
        migrations.AddField(
            model_name='carownedbydriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driverAPI.driver'),
        ),
    ]
